version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: lts/erbium
      - run: node --version
workflows:
  build-and-test:
    jobs:
      - build-and-test
